### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by eggbean** [gerazov/toggle-bool.nvim#1]
Hi. I have been using this for a while and I have found a couple of problems with it.

There is no support for capitalised/lowercase/uppercase, so each variant needs to be explicitly set. You must know about this, but as I have quite a lot of toggles, so it's less efficient than having this sorted out in the logic.

Also, it gets confused by partial words. e.g.

`Yes` ←→ `No`
`Allow` ←→ `Deny`
`All` ←→ `None`

It will see `All` in `Allow` and change it to `Noneow`. It would see `No` in `None` and change it to `Yesne`, so I have to stick with your vimscript version for now.

I have a very hard time understanding lua for some reason. I am fine with vimscript, but lua is so confusing for me even when just setting plugin configuration, so I'm unable to help out with this at this stage.

**Comment by gerazov** [comment]
`vim-toggle-bool` relied on [switch.vim](https://github.com/AndrewRadev/switch.vim) for the capitalization. This can be added to the logic using lua `string` methods, e.g. see [lua string methods](https://www.tutorialspoint.com/lua/lua_strings.htm) :+1: 

Partial words can be fixed using regex. A quick workaround would be to sort the entries in the table, but for this we would need to make it a numeric table (currently it's a associative table so we can't control the order), e.g. see [this](https://stackoverflow.com/a/55109411/8196612).

Lua is quite simple and has similarities with Python and JS. You can see all the details in 15 min (if you ignore metatables and objects, which are confusing). Here's a short guide [Learn Lua in Y minutes](https://learnxinyminutes.com/docs/lua/). One useful tip for Neovim is if you wanna debug via printing you can print tables using `print(vim.inspect(table_name))`.

For me VimL was always cryptic (even after going through the whole [Learn Vimscript the Hard Way](https://learnvimscriptthehardway.stevelosh.com/)). In fact, if it wasn't for the help of @AndrewRadev I wouldn't be able to make `vim-toggle-bool` in the first place :sweat_smile: 

To get started with Lua for Neovim plugins I suggest @David-Kunz [Writing Plugins - It's Never Been Easier (NeovimConf 2022)](https://www.youtube.com/watch?v=PdaObkGazoU)

I'll allocate some time on fixing these if you don't beat me to it :slightly_smiling_face:

**Comment by gerazov** [comment]
Fixed with #2
